//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace milanexamschedularapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<courseInfo> courseInfoes { get; set; }
    
        public virtual ObjectResult<listofdates_Result> listofdates(string courseid_value)
        {
            var courseid_valueParameter = courseid_value != null ?
                new ObjectParameter("courseid_value", courseid_value) :
                new ObjectParameter("courseid_value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listofdates_Result>("listofdates", courseid_valueParameter);
        }
    }
}
